id = "azure-pipelines"
name = "Azure pipelines"
version = "0.1.0"
schema_version = 1
authors = ["ba3n3 <null@github.com>"]
description = "Syntax highlighting for Azure Pipeline files"
repository = "https://github.com/ba3n3/zed-azure-pipelines"

[language_servers.azure-pipelines]
name = "Azure Pipelines Language Server"
language = "YAML"
